services:

  postgres:
    container_name: postgres
    image: dockerhub.timeweb.cloud/library/postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command:
      - "postgres"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=/tmp/logs"
    volumes:
      - ${PWD}/bot_data/database:/var/lib/postgresql/data
      - ${PWD}/bot_data/logs/postgres:/var/postgres/logs
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U admin
      interval: 10s
      timeout: 10s
      retries: 3

  pyro_bot:
    container_name: pyro_bot
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ${PWD}/bot_data/logs/bot:/bot/logs
    depends_on:
      postgres:
        condition: service_healthy