services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command:
      - "postgres"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=/tmp/logs"
    volumes:
      - ./bot_data/database:/var/lib/postgresql/data
      - ./bot_data/logs/postgres:/var/postgres/logs
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U admin
      interval: 10s
      timeout: 10s
      retries: 3

  pyro_bot:
    container_name: pyro_bot
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ${PWD}/bot_data/logs/bot:/bot/logs
      - ${PWD}/${API_NAME}.session:/bot/${API_NAME}.session
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy